Work
LiaSolo/to-do-list pull request #1
Opened 2023-10-25 12:37 UTC by LiaSolo

2023-10-25 14:10 UTC, kirill-stupakov requested changes

2023-10-25 14:10 UTC, kirill-stupakov commented on package.json
> +    "@mui/material": "^5.14.13",
emotion и mui нигде не используются

либо через `npm remove <packages>`
либо через удаление ручками в этом файле и потом `npm install`

2023-10-25 14:10 UTC, kirill-stupakov commented on src/App.tsx
> +
пустые строчки

2023-10-25 14:10 UTC, kirill-stupakov commented on src/Store.tsx
С большой буквы обычно называются только компоненты

2023-10-25 14:10 UTC, kirill-stupakov commented on src/TodoItem.tsx
`level` и `state` лучше сделать через union types

2023-10-25 14:10 UTC, kirill-stupakov commented on src/assets/react.svg
надо удолить

2023-10-25 14:10 UTC, kirill-stupakov commented on src/compareNotes.tsx
> +    const level = elem.level
```TS
const { completed, level } = elem;
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/compareNotes.tsx
```TS
const levelsByImportance = ['LOW', 'MEDIUM', 'CRITICAL'];

export function compareNotes(elem1:TodoItem, elem2: TodoItem) {
    if (elem1.completed === elem2.completed) {
        return levelsByImportance.indexOf(elem1.level) - levelsByImportance.indexOf(elem2.level);
    }
    
    // и т.д.
}
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Buttons/Buttons.tsx
> +const Buttons: FC<Props> = ({ onClick, isDisabled=false, hasIcon=false, hasPadding, icon, iconSize, btnWidth='auto', text, btnColor }) => {
единственное число

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Buttons/Buttons.tsx
> +                </div> : ''}
добавить проп `iconSrc`

```TSX
{hasIcon && (
    <img
        className={styles.btnIcons} 
        style={{
            height: iconSize, 
            width: iconSize, 
        }}
        src={iconSrc}
    />
    }
```

А использовать так:

```TS
import addIconSrc from 'assets/add.svg';

<Button iconSrc={addIconSrc} />
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Header/Header.tsx
> +          <form  action='' method='get'>
`<form>` лучше не использовать, если ты с сервером не взаимодействуешь тут

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Buttons/Buttons.tsx
> +    btnWidth?: string;
number

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Buttons/Buttons.tsx
> +    hasPadding?: string;
`className? string`

Добавлять его к классу кнопки, и управлять паддингом из компонента, который использует Button

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Buttons/Buttons.tsx
> +    text: string;
`?: string`

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Buttons/Buttons.tsx
> +    btnColor: string;
`variant?: 'primary' | 'secondary' | 'danger' | 'success'`

```TS
const mapVariantToColor = {
   primary: '#aaaa',
   ...
}
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Header/Header.tsx
> +            onClick={handleAddNoteClick}
```onClick={createEmptyTodo}```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Menu/Menu.module.scss
> +    width: 573px;
размеры тут не нужны

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Menu/Menu.module.scss
> +    width: 334px;
тут тоже размеры не нужны

2023-10-25 14:10 UTC, kirill-stupakov commented on src/Store.tsx
> +    saveChanges: (changedTodo: TodoItem) => set(state => {
replaceItem

А логику по complete и edit лучше сделать отдельными функциями

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Menu/Menu.tsx
> +        setShowMenu(false)
```TS
const unsavedItem = {
            ...item,
            state: 'edit'
        }
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Note/Note.tsx
> +    const [textTitle, setTextTitle] = useState(item.title)
лучше чтобы в начале компонента вызывались хуки, а потом всё остальное

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Note/Note.tsx
> +    const [selectedLevel, setLevel] = useState('MEDIUM');
```TS
useState<TodoImportanceLevel>('medium');
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/Note/Note.tsx
> +            <div className={isSaved ? classNames(styles.bodyNoteBox, styles.noBorder) : styles.bodyNoteBox}>
```
classNames(styles.bodyNoteBox, isSaved && noBorder)
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/TodoList/TodoList.module.scss
> +    padding: 64px 128px 64px 128px;
padding: 64px 128px;

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/selectLevels/selectLevels.tsx
> +    }
```TS
const handleLevelChange = (newLevel: string) => {
        setShowOptions(!isShowOptions);
        setLevel(newLevel);
    }
```

2023-10-25 14:10 UTC, kirill-stupakov commented on src/components/selectLevels/selectLevels.tsx
> +                    <div className={styles.dropDownOptions}
Можно будет воспользоваться массивом из level-ов


```TS
const levelsByImportance = ['a', 'b', 'c'] as const;

type Level = typeof levelsByImportance[number];
```

Тут можно промапаться по этому массиву

2023-10-25 14:10 UTC, kirill-stupakov commented on src/index.css
Отсюда можешь вообще всё убрать (но возможно где-то вёрстка поедет)

2023-10-25 19:08 UTC, kirill-stupakov requested changes

2023-10-25 19:08 UTC, kirill-stupakov commented on .vite/deps/_metadata.json
Папочку .vite надо бы добавить в .gitignore

2023-10-25 19:08 UTC, kirill-stupakov commented on src/compareNotes.tsx
> +        return 10;
1 и -1

2023-10-25 19:08 UTC, kirill-stupakov commented on src/components/Header/Header.tsx
> +            ></input>
Если внутри тэга ничего нет, можно писать `<tag />`

2023-10-25 19:24 UTC, LiaSolo commented on src/compareNotes.tsx
> +        return 10;
чем тебе 10 не угодило

2023-10-25 19:48 UTC, kirill-stupakov commented on src/compareNotes.tsx
> +        return 10;
![Screenshot_20231025_224404_Chrome.jpg](https://github.com/LiaSolo/to-do-list/assets/58115151/bc130e34-b89c-47e6-81ba-7a8d35813b29)

![Screenshot_20231025_224645_Chrome.jpg](https://github.com/LiaSolo/to-do-list/assets/58115151/eb92dab9-1e64-4b12-a9b2-4c93788e1b8c)

2023-10-25 19:49 UTC, kirill-stupakov commented on src/compareNotes.tsx
> +        return 10;
Кажется 1 тут лучше подходит

2023-10-25 19:54 UTC, kirill-stupakov commented on src/compareNotes.tsx
> +        return 10;
И вообще
```TS
return item1.completed ? 1 : -1;
```

2023-10-28 09:54 UTC, kirill-stupakov requested changes

2023-10-28 09:54 UTC, kirill-stupakov commented on src/serverMethods.ts
> +    console.log(json);
Логи

2023-10-28 09:54 UTC, kirill-stupakov commented on src/serverMethods.ts
> +    console.log(json);
Логи

2023-10-28 09:54 UTC, kirill-stupakov commented on src/serverMethods.ts
> +    console.log(json);
Логи

2023-10-28 09:54 UTC, kirill-stupakov commented on src/serverMethods.ts
> +    console.log(json);
Логи

2023-10-28 09:54 UTC, kirill-stupakov commented on src/store.ts
> +    isAddingDisabled: false,
Это уже не нужно, т.к. у тебя есть `newTodoId`

2023-10-28 12:33 UTC, kirill-stupakov approved these changes

2023-10-28 12:33 UTC, merged